import type { ProfessionalContentSource } from "../../domain/content";

export const professionalContent = {
  experiences: [
    {
      id: "experience-sopra-steria",
      organization: "Sopra Steria",
      logoAssetId: "organization-logo-sopra-steria",
      order: 10,
      featured: true,
      roles: [
        {
          id: "role-sopra-senior-software-engineer",
          title: "Senior Software Engineer",
          dates: { start: "2025-08", end: { kind: "present" } },
          location: "Bengaluru, Karnataka, India",
          engagement: {
            relationship: "customer",
            organization: "Airbus",
          },
          summary:
            "Enterprise application modernization from PHP to FastAPI and React.",
          order: 10,
          responsibilities: [
            {
              id: "claim-sopra-modernization",
              order: 10,
              text: "Co-designed a hybrid PHP-to-FastAPI/React modernization architecture based on the Strangler Fig pattern, implementing AWS ALB listener-rule URL rewrite transforms for phased routing without a big-bang cutover.",
            },
            {
              id: "claim-sopra-identity-authorization",
              order: 20,
              text: "Designed and implemented a request-scoped user context and authorization layer using reusable FastAPI dependencies, separating identity, permissions, and scoped/global configuration while selectively caching frequently accessed state across migrated APIs; designed shared identity, authorization, and configuration state across FastAPI and React using dependency injection, client-side persistence, and periodic synchronization.",
            },
            {
              id: "claim-sopra-workflow-migration",
              order: 30,
              text: "Owned end-to-end migration of core workflow-management features and backend APIs from session-based PHP to FastAPI/React, defining REST API contracts and client/server state boundaries; delivered configurable forms and endpoints, a reusable multi-select React component, and a multi-field user-search API.",
            },
            {
              id: "claim-sopra-platform-capabilities",
              order: 40,
              text: "Migrated 2 cross-cutting platform capabilities - User Impersonation and Audit Logging - with authorization-aware client state, server-side authorization enforcement, and filterable, paginated audit logs with React infinite scroll.",
            },
            {
              id: "claim-sopra-payload-reduction",
              order: 50,
              text: "Reduced primary data-grid API payloads from ~1.5-2 MB to <1 MB through response shaping and Gzip compression, meeting the ALB-to-Lambda 1 MB response limit for deeply nested workflow data.",
            },
            {
              id: "claim-sopra-leadership",
              order: 60,
              text: "Led delivery for 3 engineers, reviewed PRs across Sopra, Airbus, and partner teams, and introduced database-backed pytest fixtures for persistence and authorization testing, reducing reliance on mock-heavy tests.",
            },
          ],
          technologyIds: [
            "skill-python",
            "skill-fastapi",
            "skill-react",
            "skill-rest-api-design",
            "skill-aws-alb",
            "skill-aws-lambda",
            "skill-dependency-injection",
            "skill-caching",
            "skill-pytest",
            "skill-gzip-compression",
          ],
        },
      ],
    },
    {
      id: "experience-gainfront",
      organization: "Gainfront",
      logoAssetId: "organization-logo-gainfront",
      order: 20,
      featured: true,
      roles: [
        {
          id: "role-gainfront-software-developer",
          title: "Software Developer",
          dates: {
            start: "2023-06",
            end: { kind: "date", value: "2025-08" },
          },
          location: "Bengaluru, Karnataka, India",
          summary:
            "Modernized supplier-facing modules and delivered greenfield modules from requirements through release.",
          order: 10,
          responsibilities: [
            {
              id: "claim-gainfront-modernization",
              order: 10,
              text: "Modernized 5 supplier-facing modules - Supplier Profile, Discovery, Purchasing, Registration, and Dashboards - from server-rendered Django to decoupled DRF APIs and a Vue.js/Quasar SPA, separating backend contracts from frontend releases and supporting configuration-driven country/customer form variants.",
            },
            {
              id: "claim-gainfront-greenfield",
              order: 20,
              text: "Designed and delivered backend services and Vue/Quasar interfaces for 4 greenfield modules - Request for Price, Target Report, Spend Analytics, and Itemized Quote - from requirements and API/data design through release, supporting enterprise onboarding and upsell workflows.",
            },
            {
              id: "claim-gainfront-rabbitmq-prototype",
              order: 30,
              text: "Designed a RabbitMQ-based asynchronous document-processing prototype for contract, invoice, and supplier-certificate workflows, covering queue-based processing, retries/backoff, and DLQs.",
            },
            {
              id: "claim-gainfront-authentication",
              order: 40,
              text: "Implemented JWT authentication with Redis-backed token revocation and API rate limiting; contributed to AWS ECS/RDS architecture.",
            },
            {
              id: "claim-gainfront-testing",
              order: 50,
              text: "Helped raise backend test coverage by ~45 percentage points (~40% to ~85%) by adding pytest coverage for new and migrated flows and strengthening CI/linting checks; reinforced maintainability through code reviews and design discussions.",
            },
          ],
          technologyIds: [
            "skill-python",
            "skill-django",
            "skill-django-rest-framework",
            "skill-vue-js",
            "skill-quasar",
            "skill-rabbitmq",
            "skill-jwt",
            "skill-redis",
            "skill-api-rate-limiting",
            "skill-aws-ecs",
            "skill-aws-rds",
            "skill-pytest",
          ],
        },
      ],
    },
    {
      id: "experience-marsdevs",
      organization: "MarsDevs",
      logoAssetId: "organization-logo-marsdevs",
      order: 30,
      featured: false,
      roles: [
        {
          id: "role-marsdevs-software-engineer",
          title: "Software Engineer",
          dates: {
            start: "2020-11",
            end: { kind: "date", value: "2023-06" },
          },
          location: "Pune, Maharashtra, India",
          summary:
            "Delivered backend and frontend features, integrations, releases, and testing improvements across client projects.",
          order: 10,
          responsibilities: [
            {
              id: "claim-marsdevs-polestar",
              order: 10,
              text: "Delivered full-stack features for Polestar across Django/DRF APIs and Vue.js/Nuxt.js frontends, covering regional workflows, finance and payment flows, third-party API integrations, custom middleware/commands/signals, releases, and mentoring interns.",
            },
            {
              id: "claim-marsdevs-castapp",
              order: 20,
              text: "Reduced Castapp video-generation time by 60% by optimizing Python/Flask processing and GCP task orchestration while supporting React integration and improving React components.",
            },
            {
              id: "claim-marsdevs-document-ai",
              order: 30,
              text: "Built and delivered a Google Cloud Document AI processor for Afto, tyre-health APIs and ReportLab PDF reports for TyreExpress, and backend test improvements that increased backend test coverage by 35% for Medtrics.",
            },
          ],
          technologyIds: [
            "skill-python",
            "skill-django",
            "skill-django-rest-framework",
            "skill-flask",
            "skill-vue-js",
            "skill-nuxt-js",
            "skill-react",
            "skill-gcp",
            "skill-google-cloud-document-ai",
            "skill-reportlab",
          ],
        },
      ],
    },
  ],
  credibilityHighlights: [
    {
      id: "highlight-modernization-architecture",
      lead: "Co-designed a phased PHP-to-FastAPI/React modernization architecture.",
      detail:
        "As a Senior Software Engineer at Sopra Steria on the Airbus engagement, implemented Strangler Fig routing with AWS ALB URL rewrites to avoid a big-bang cutover.",
      supportingClaimIds: ["claim-sopra-modernization"],
      order: 10,
    },
    {
      id: "highlight-full-stack-delivery",
      lead: "Designed and delivered 4 greenfield modules from requirements through release.",
      detail:
        "As a Software Developer at Gainfront, built DRF services and Vue/Quasar interfaces for Request for Price, Target Report, Spend Analytics, and Itemized Quote.",
      supportingClaimIds: ["claim-gainfront-greenfield"],
      order: 20,
    },
    {
      id: "highlight-delivery-leadership",
      lead: "Led delivery for 3 engineers and reviewed PRs across Sopra, Airbus, and partner teams.",
      detail:
        "As a Senior Software Engineer at Sopra Steria, guided delivery while strengthening persistence and authorization testing with database-backed pytest fixtures.",
      supportingClaimIds: ["claim-sopra-leadership"],
      order: 30,
    },
    {
      id: "highlight-api-payload",
      lead: "Reduced primary data-grid API payloads from ~1.5-2 MB to <1 MB.",
      detail:
        "As a Senior Software Engineer at Sopra Steria, used response shaping and Gzip compression to meet the ALB-to-Lambda 1 MB response limit.",
      supportingClaimIds: ["claim-sopra-payload-reduction"],
      order: 40,
    },
    {
      id: "highlight-test-coverage",
      lead: "Helped raise backend test coverage by ~45 percentage points (~40% to ~85%).",
      detail:
        "As a Software Developer at Gainfront, added pytest coverage for new and migrated flows and strengthened CI and linting checks.",
      supportingClaimIds: ["claim-gainfront-testing"],
      order: 50,
    },
  ],
  skills: [
    { id: "skill-python", name: "Python" },
    { id: "skill-fastapi", name: "FastAPI" },
    { id: "skill-django", name: "Django" },
    { id: "skill-django-rest-framework", name: "Django REST Framework" },
    { id: "skill-flask", name: "Flask" },
    { id: "skill-sqlalchemy", name: "SQLAlchemy" },
    { id: "skill-pydantic", name: "Pydantic" },
    { id: "skill-rest-api-design", name: "REST API Design" },
    { id: "skill-javascript", name: "JavaScript" },
    { id: "skill-react", name: "React" },
    { id: "skill-redux", name: "Redux" },
    { id: "skill-vue-js", name: "Vue.js" },
    { id: "skill-nuxt-js", name: "Nuxt.js" },
    { id: "skill-quasar", name: "Quasar" },
    { id: "skill-html-css", name: "HTML/CSS" },
    { id: "skill-jest", name: "Jest" },
    { id: "skill-sql", name: "SQL" },
    { id: "skill-postgresql", name: "PostgreSQL" },
    { id: "skill-mysql", name: "MySQL" },
    { id: "skill-mongodb", name: "MongoDB" },
    { id: "skill-redis", name: "Redis" },
    { id: "skill-rabbitmq", name: "RabbitMQ" },
    { id: "skill-aws-alb", name: "AWS ALB" },
    { id: "skill-aws-lambda", name: "AWS Lambda" },
    { id: "skill-aws-ecs", name: "AWS ECS" },
    { id: "skill-aws-fargate", name: "AWS Fargate" },
    { id: "skill-aws-rds", name: "AWS RDS" },
    { id: "skill-aws-s3", name: "AWS S3" },
    { id: "skill-aws-cloudfront", name: "AWS CloudFront" },
    { id: "skill-gcp", name: "GCP" },
    { id: "skill-docker", name: "Docker" },
    { id: "skill-ci-cd", name: "CI/CD" },
    {
      id: "skill-authentication-authorization",
      name: "Authentication & Authorization",
    },
    { id: "skill-dependency-injection", name: "Dependency Injection" },
    { id: "skill-caching", name: "Caching" },
    {
      id: "skill-performance-optimization",
      name: "Performance Optimization",
    },
    { id: "skill-pytest", name: "pytest" },
    { id: "skill-code-review", name: "Code Review" },
    { id: "skill-solid-principles", name: "SOLID Principles" },
    { id: "skill-jwt", name: "JWT" },
    { id: "skill-api-rate-limiting", name: "API Rate Limiting" },
    { id: "skill-gzip-compression", name: "Gzip Compression" },
    {
      id: "skill-google-cloud-document-ai",
      name: "Google Cloud Document AI",
    },
    { id: "skill-reportlab", name: "ReportLab" },
  ],
  skillGroups: [
    {
      id: "skill-group-languages",
      category: "languages",
      name: "Languages",
      order: 10,
      skills: [
        { skillId: "skill-python", order: 10 },
        { skillId: "skill-javascript", order: 20 },
        { skillId: "skill-sql", order: 30 },
      ],
    },
    {
      id: "skill-group-backend-apis",
      category: "backend",
      name: "Backend and APIs",
      order: 20,
      skills: [
        { skillId: "skill-fastapi", order: 10 },
        { skillId: "skill-django", order: 20 },
        { skillId: "skill-django-rest-framework", order: 30 },
        { skillId: "skill-flask", order: 40 },
        { skillId: "skill-sqlalchemy", order: 50 },
        { skillId: "skill-pydantic", order: 60 },
        { skillId: "skill-rest-api-design", order: 70 },
        { skillId: "skill-authentication-authorization", order: 80 },
        { skillId: "skill-dependency-injection", order: 90 },
        { skillId: "skill-jwt", order: 100 },
        { skillId: "skill-api-rate-limiting", order: 110 },
        { skillId: "skill-gzip-compression", order: 120 },
        { skillId: "skill-reportlab", order: 130 },
      ],
    },
    {
      id: "skill-group-frontend",
      category: "frontend",
      name: "Frontend",
      order: 30,
      skills: [
        { skillId: "skill-react", order: 10 },
        { skillId: "skill-redux", order: 20 },
        { skillId: "skill-vue-js", order: 30 },
        { skillId: "skill-nuxt-js", order: 40 },
        { skillId: "skill-quasar", order: 50 },
        { skillId: "skill-html-css", order: 60 },
      ],
    },
    {
      id: "skill-group-data-processing",
      category: "data",
      name: "Databases, caching, and asynchronous processing",
      order: 40,
      skills: [
        { skillId: "skill-postgresql", order: 10 },
        { skillId: "skill-mysql", order: 20 },
        { skillId: "skill-mongodb", order: 30 },
        { skillId: "skill-redis", order: 40 },
        { skillId: "skill-rabbitmq", order: 50 },
        { skillId: "skill-caching", order: 60 },
      ],
    },
    {
      id: "skill-group-cloud-infrastructure",
      category: "cloud",
      name: "Cloud and infrastructure",
      order: 50,
      skills: [
        { skillId: "skill-aws-alb", order: 10 },
        { skillId: "skill-aws-lambda", order: 20 },
        { skillId: "skill-aws-ecs", order: 30 },
        { skillId: "skill-aws-fargate", order: 40 },
        { skillId: "skill-aws-rds", order: 50 },
        { skillId: "skill-aws-s3", order: 60 },
        { skillId: "skill-aws-cloudfront", order: 70 },
        { skillId: "skill-gcp", order: 80 },
        { skillId: "skill-google-cloud-document-ai", order: 90 },
        { skillId: "skill-docker", order: 100 },
      ],
    },
    {
      id: "skill-group-quality-tooling",
      category: "tooling",
      name: "Testing, quality, and developer tooling",
      order: 60,
      skills: [
        { skillId: "skill-pytest", order: 10 },
        { skillId: "skill-jest", order: 20 },
        { skillId: "skill-ci-cd", order: 30 },
        { skillId: "skill-code-review", order: 40 },
        { skillId: "skill-solid-principles", order: 50 },
        { skillId: "skill-performance-optimization", order: 60 },
      ],
    },
  ],
  education: [
    {
      id: "education-computer-engineering",
      institution: "University of Mumbai",
      credential: "Bachelor of Engineering",
      fieldOfStudy: "Computer Engineering",
      dates: {
        start: "2016",
        end: { kind: "date", value: "2020" },
      },
      score: "CGPA 8.74/10",
      logoAssetId: "organization-logo-university-of-mumbai",
      order: 10,
    },
  ],
} satisfies ProfessionalContentSource;
