import type { SiteContentSource } from "../../domain/content";

export const siteContent = {
  identity: {
    id: "site-identity",
    displayName: "Rahul Yadav",
    roleLabel: "Senior Software Engineer",
    location: "Bangalore, Mumbai, India",
    professionalPositioning:
      "Six years building and modernizing enterprise software across Python backends and backend-heavy React and Vue products.",
    introduction:
      "I build backend systems with Python, FastAPI, Django/DRF, PostgreSQL, Redis, and AWS, focusing on API design and migration, authentication and authorization, caching, performance, and testing. My work is backend-first and full-stack in delivery: I integrate React and Vue interfaces with backend services, make technical decisions, review code, and carry features from design through release. I spent more than two years building and modernizing enterprise SaaS products at Gainfront and now contribute to an Airbus-associated modernization engagement.",
    opportunityStatement:
      "Open to Senior Backend Engineer, Senior Software Engineer/SDE II, and backend-heavy full-stack opportunities.",
    careerStart: "2020-11",
    locale: "en-IN",
  },
  seo: {
    id: "seo-defaults",
    siteName: "Rahul Yadav",
    canonicalOrigin: "https://rahuly.in",
    titleTemplate: "%s | Rahul Yadav",
    home: {
      title: "Rahul Yadav | Senior Software Engineer",
      description:
        "Senior Software Engineer Rahul Yadav has six years of experience modernizing Python backends and delivering backend-heavy React and Vue products.",
      canonicalPath: "/",
    },
    projects: {
      title: "Projects | Rahul Yadav",
      description:
        "Approved project case studies will be added in a later portfolio milestone.",
      canonicalPath: "/projects",
    },
    writings: {
      title: "Writings | Rahul Yadav",
      description:
        "Published technical writings will be added in a later portfolio milestone.",
      canonicalPath: "/writings",
    },
  },
  contacts: [
    {
      id: "contact-email",
      kind: "email",
      label: "rahulyadevx@gmail.com",
      href: "mailto:rahulyadevx@gmail.com",
      order: 10,
    },
    {
      id: "contact-phone",
      kind: "phone",
      label: "+91 96195 63665",
      href: "tel:+919619563665",
      order: 20,
    },
  ],
  socialLinks: [
    {
      id: "social-linkedin",
      platform: "linkedin",
      label: "LinkedIn",
      url: "https://linkedin.com/in/rahulyadev",
      order: 10,
    },
    {
      id: "social-github",
      platform: "github",
      label: "GitHub",
      url: "https://github.com/rahulyadev",
      order: 20,
    },
  ],
  resumeAssets: [
    {
      id: "resume-public",
      publicationStatus: "published",
      title: "Rahul Yadav resume",
      path: "/assets/resume/rahul-yadav-resume.pdf",
      mediaType: "application/pdf",
      downloadName: "rahul-yadav-resume.pdf",
    },
  ],
  images: [
    {
      id: "profile-main-400-avif",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-400.avif",
      mediaType: "image/avif",
      width: 400,
      height: 500,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-400-webp",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-400.webp",
      mediaType: "image/webp",
      width: 400,
      height: 500,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-400-jpeg",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-400.jpg",
      mediaType: "image/jpeg",
      width: 400,
      height: 500,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-640-avif",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-640.avif",
      mediaType: "image/avif",
      width: 640,
      height: 800,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-640-webp",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-640.webp",
      mediaType: "image/webp",
      width: 640,
      height: 800,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-640-jpeg",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-640.jpg",
      mediaType: "image/jpeg",
      width: 640,
      height: 800,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-800-avif",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-800.avif",
      mediaType: "image/avif",
      width: 800,
      height: 1000,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-800-webp",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-800.webp",
      mediaType: "image/webp",
      width: 800,
      height: 1000,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-main-800-jpeg",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-800.jpg",
      mediaType: "image/jpeg",
      width: 800,
      height: 1000,
      decorative: false,
      altText: "Portrait of Rahul Yadav smiling in a floral kurta.",
    },
    {
      id: "profile-compact-96-avif",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-96.avif",
      mediaType: "image/avif",
      width: 96,
      height: 120,
      decorative: true,
      altText: "",
    },
    {
      id: "profile-compact-96-webp",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-96.webp",
      mediaType: "image/webp",
      width: 96,
      height: 120,
      decorative: true,
      altText: "",
    },
    {
      id: "profile-compact-96-jpeg",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-96.jpg",
      mediaType: "image/jpeg",
      width: 96,
      height: 120,
      decorative: true,
      altText: "",
    },
    {
      id: "profile-compact-192-avif",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-192.avif",
      mediaType: "image/avif",
      width: 192,
      height: 240,
      decorative: true,
      altText: "",
    },
    {
      id: "profile-compact-192-webp",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-192.webp",
      mediaType: "image/webp",
      width: 192,
      height: 240,
      decorative: true,
      altText: "",
    },
    {
      id: "profile-compact-192-jpeg",
      publicationStatus: "published",
      path: "/assets/profile/rahul-yadav-portrait-compact-192.jpg",
      mediaType: "image/jpeg",
      width: 192,
      height: 240,
      decorative: true,
      altText: "",
    },
  ],
  profileImage: {
    id: "profile-image",
    mainAssetIds: [
      "profile-main-400-avif",
      "profile-main-400-webp",
      "profile-main-400-jpeg",
      "profile-main-640-avif",
      "profile-main-640-webp",
      "profile-main-640-jpeg",
      "profile-main-800-avif",
      "profile-main-800-webp",
      "profile-main-800-jpeg",
    ],
    compactAssetIds: [
      "profile-compact-96-avif",
      "profile-compact-96-webp",
      "profile-compact-96-jpeg",
      "profile-compact-192-avif",
      "profile-compact-192-webp",
      "profile-compact-192-jpeg",
    ],
  },
} satisfies SiteContentSource;
